### ISSUE TITLE
Failed to get rewards

### ISSUE THREAD

**Issue by reth3** [serenita-org/ethstaker.tax#78]
I'm getting this error message:

> Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer X, slot Y

Please let me know if you need the validator number.

**Comment by eth2353** [comment]
Found your error in the logs, that issue should be fixed now, let me know if you run into anything else!

**Comment by MrYukonC1** [comment]
> Found your error in the logs, that issue should be fixed now, let me know if you run into anything else!

Hello, I am getting this error today.

**Comment by eth2353** [comment]
I fixed the data for a few blocks, please check if you're still getting an error

**Comment by MrYukonC1** [comment]
Hello, that appears to have fixed it. Thank you.

**Comment by MrYukonC1** [comment]
I have a colleague that is still getting the error on a different slot than he was yesterday.
